### ISSUE TITLE
SSL not working when using acutal NRPE release !

### ISSUE THREAD

**Issue by fskale** [andreas-marschke/nagios-nrpe#3]
Hi,
i wanted to inform you, that your client SSL implementation will not work with recent NRPE releases. (NAGIOS-NRPE-SERVER).
Since i use Nagios::NRPE::Client against a standard NRPE server, i noticed, that:
1.) NRPE changed to TLSv1 in 2014
2.) NRPE uses ADH cipher.
So, when calling with ssl => 1 it will fail badly, because the default setting of IO::Socket::SSL is to use SSLv23 which actually wants to have a certificate. The call  will not succeed until you set the right SSL_version and SSL_cipher_list.
Also consider to not use deprecated IO::Socket::SSL Options.

My changes in Client.pm (beginning at line 146).
This works for me though:
```
my $socket;
  if($self->{ssl}) {
    eval {
        # required for new IO::Socket::SSL versions
        use IO::Socket::SSL;
    };

        $socket = IO::Socket::SSL->new(
        # where to connect
        PeerHost => $self->{host},
        PeerPort => $self->{port},
        SSL_verify_mode => SSL_VERIFY_NONE,
        SSL_version => 'TLSv1',
        SSL_cipher_list => 'ADH'
        ) or die "failed connect or ssl handshake: $!,$SSL_ERROR";

  } else {
    $socket = IO::Socket::INET->new(
                    PeerAddr => $self->{host},
                    PeerPort => $self->{port},
                    Proto    => 'tcp',
                    Type     => SOCK_STREAM) or die "ERROR: $@ \n";
  }
```

Rgds.

Franz

**Comment by andreas-marschke** [comment]
Thanks! Feel free to fork and submit a pull request with the changes you've made. I'm sure we can get this back to where it's supposed to be!

**Comment by andreas-marschke** [comment]
Issue fixed with merging the pull request. Want to take over maintainership of the project?

I'm not an Admin anymore and have no use for this. I think it should be easy for you to reach me by mail to discuss this.
